### ISSUE TITLE
Relative path for `img` does not resolve

### ISSUE THREAD

**Issue by RickStanley** [riot/parcel-plugin-riot#11]
When using something like: `<img src="../img/my-image.png">`, the image is not processed through parcel and the path is not resolved. I'm wondering if it is a issue with parcel itself. Please let me know.

Structure example:

```bash
src/
├── components/
│   └── app.riot <--- `<img>` is declared here
├── img/
│    └── my-image.png
└── index.html
```

**Comment by RickStanley** [comment]
I see that using `import` works, like `import image from '../img/foo.jpg;'`.
But shouldn't the one above work as well? Or is it an expected behavior?

**Comment by GianlucaGuarini** [comment]
No parcel can't identify images in Riot.js templates. Riot.js templates will be converted to javascript strings via @riotjs/compiler
You could however import them simply by using:

```html
<my-component>
   <img src={ import('./path/to/the/image.jpg') }/>
</my-component>
```

I don't know why this strategy should be better than simply embedding the image src but at least it should work.
