### ISSUE TITLE
Parcel v2 support

### ISSUE THREAD

**Issue by mgray-lab4motion** [riot/parcel-plugin-riot#17]
Since Parcel v2 is already in beta, is there an option to prepare, on a separate branch, a parcel plugin for the upcoming version?

**Comment by GianlucaGuarini** [comment]
I will work on it as soon as Parcel v2 will be released. For a script [less than 50 lines of code](https://github.com/riot/parcel-plugin-riot/blob/master/RiotAsset.js) is not worth starting experimenting with something not yet released
