### ISSUE TITLE
Idiomatic way to use preprocessor? (i.e. Pug template)

### ISSUE THREAD

**Issue by bminer** [riot/parcel-plugin-riot#5]
For example, the Riot CLI tool provides a mechanism to use Pug as a template engine.  How do you do this with parcel-plugin-riot?

Thanks!

**Comment by bminer** [comment]
Also started some discussion here: https://github.com/parcel-bundler/parcel/issues/1174

**Comment by bminer** [comment]
One idea is to use the ES6 config file shown on this page:
https://riot.js.org/guide/compiler/#pre-compilation

(if you scroll down to that section).  This plugin could read that file to facilitate the compilation process.

**Comment by bminer** [comment]
Also see #4.  This idea is reflected in that PR, which  should probably be merged.

**Comment by GianlucaGuarini** [comment]
fixed in v2.1.0 thanks for reporting it
