### ISSUE TITLE
Transfer this plugin under the riot organization

### ISSUE THREAD

**Issue by GianlucaGuarini** [riot/parcel-plugin-riot#6]
Hi @andruschka thanks for this plugin. I am updating all the riot loaders preparing them for the new upcoming 4 release. Could you please move this plugin under the https://github.com/riot organization?

You should also grant the npm read/write permissions to the `@riotjs` organization allowing me to publish the new versions `npm access grant read-write riotjs parcel-plugin-riot`.

Thanks you

**Comment by andruschka** [comment]
Hello. Of course - I will grant you the permissions and transfer this repo.

**Comment by andruschka** [comment]
There is a problem with the code `npm access grant read-write riotjs parcel-plugin-riot`. It seems that `riotjs` is not the right argument here. 
-> `Second argument used incorrect format`

**Comment by andruschka** [comment]
I think it needs a `@scope:team` argument

**Comment by andruschka** [comment]
I also cannot transfer this repo. 
Note: `You don’t have the permission to create repositories on riot`

**Comment by GianlucaGuarini** [comment]
@andruschka could you please grant me the permissions, I will transfer the repo and grant you the permissions back.

Sorry for npm you could use 
`npm access grant read-write @riotjs:developers parcel-plugin-riot`

Thank you

**Comment by andruschka** [comment]
Ok. 
For the npm command I still get:
`404 Not Found : -/team/%40riotjs/developers/package`
😆

**Comment by andruschka** [comment]
Btw. I requested a transfer for github.

**Comment by andruschka** [comment]
And I added you as owner of parcel-plugin-riot on npm. 
I think that should do?

**Comment by GianlucaGuarini** [comment]
@andruschka ok the repo was properly transferred and you still have the `write` permission to it! ein Problem weniger 😄 

For npm let's try this:
```
npm owner add gianlucaguarini parcel-plugin-riot
```

**Comment by GianlucaGuarini** [comment]
Ok I have just realized you already did it. Thank you so much I will work on the source code ASAP. Have a nice day

**Comment by andruschka** [comment]
NP. Have fun coding. :-)
