### ISSUE TITLE
scopedCSS() returns an error `css.replace is not a function`

### ISSUE THREAD

**Issue by nibushibu** [riot/parcel-plugin-riot#9]
I am trying to compile `.riot` file that includes SASS(scss) codes with parcel.
But compilation fails with the following error:

```
🚨  /path-to-my-project/Getup/src/riot/my-app.riot: css.replace is not a function
    at scopedCSS (/path-to-my-project/Getup/node_modules/@riotjs/compiler/dist/index.js:291:14)
    at css (/path-to-my-project/Getup/node_modules/@riotjs/compiler/dist/index.js:339:5)
    at args (/path-to-my-project/Getup/node_modules/curri/curri.js:20:9)
    at args (/path-to-my-project/Getup/node_modules/cumpa/cumpa.js:24:48)
    at compile (/path-to-my-project/Getup/node_modules/@riotjs/compiler/dist/index.js:2024:4)
    at RiotAsset.generate (/path-to-my-project/Getup/node_modules/@riotjs/parcel-plugin-riot/RiotAsset.js:31:25)
Compile the sass code in riot/my-app.riot
```

Here is my working repository:
https://github.com/nibushibu/Getup/tree/riot4-parcel-scss-in-riot

I'm sorry if I have basically overlooked settings etc. but I would appreciate your advice.

**Comment by GianlucaGuarini** [comment]
I am sorry but I can not reproduce the issue. Could you please update your riot dependencies?

**Comment by nibushibu** [comment]
@GianlucaGuarini Thank you for your reply.
I will try to find out the cause again.

**Comment by ShiMeiWo** [comment]
@GianlucaGuarini 
I got succeed to compile when I tried to use the callback of `registerPreprocessor()` that returns `css.css.toString()`:
```
// riot.config.js
var registerPreprocessor = require('@riotjs/compiler').registerPreprocessor
var sass = require('node-sass')

registerPreprocessor('css', 'scss', function(code, { options }) {
  const { file } = options

  console.log('Compile the sass code in', file)

  const css = sass.renderSync({
    data: code
  })

  return {
    code: css.css.toString(), // here!
    map: null
  }
})

module.exports = {
  hot: false,
  css: 'scss'
}
```
@nibushibu 
Pls try the workaround!
上記の回避策を試してみてください。

**Comment by nibushibu** [comment]
@ShiMeiWo Great! Thank you for your suggestion.
I succeeded in compiling `scss` in `.riot` file.

ありがとうございます！

**Comment by GianlucaGuarini** [comment]
@ShiMeiWo that's not a workaround, that's just the new API 😄 
I think the `css: 'scss'` option is not needed either

**Comment by GianlucaGuarini** [comment]
I think we can close this issue. @nibushibu please let me know if you will find other issue. Thank you guys

**Comment by nibushibu** [comment]
Oops, I'm sorry I didn't close it.
Thank you!
